/*
 * FIDO2 credential store — TROPIC01-backed.
 *
 * Each FIDO2 credential maps 1:1 to:
 *   - TROPIC01 ECC slot N (0..28)         — Ed25519 private key, on chip
 *   - TROPIC01 R-mem slot N+1             — metadata (rp_id_hash, nonce, ...)
 *
 * Slots 29-31 are reserved for OpenPGP card sig/dec/aut (see
 * firmware/src/openpgp/pgp_keys.h).
 *
 * Private keys are generated by lt_ecc_key_generate inside the
 * TROPIC01 chip — they NEVER exist in STM32 RAM or flash.  Signatures
 * come from lt_ecc_eddsa_sign which performs the EdDSA computation
 * (RFC 8032) on-chip.  This is the core security property of the
 * device: a firmware compromise cannot exfiltrate FIDO credentials.
 *
 * Signature counter: a single SHARED monotonic counter (TROPIC01 hw
 * counter 0).  Per WebAuthn Level 2 §6.1.1 a shared counter is
 * compliant.  Initialized to TR01_MCOUNTER_VALUE_MAX (0xFFFFFFFE) on
 * first use, then decremented per assertion; observed signCount =
 * MAX − chip_value, so it increases over time.  At 1 signature/sec
 * continuous the counter exhausts after ~136 years.
 *
 * The signcount peek/commit pattern (Phase 4 cpp-reviewer audit
 * finding): peek returns the count for the next assertion WITHOUT
 * advancing; commit advances.  Callers run peek → build response →
 * commit.  A build-failure path never advances the on-chip counter
 * so it stays in sync with what the relying party expects.
 *
 * Future work — per-credential counters
 * (if RP compatibility testing shows a benefit). Phase 5 keeps it shared.
 */

#ifndef NIXTROPIC_FIDO_HID_CREDSTORE_H
#define NIXTROPIC_FIDO_HID_CREDSTORE_H

#include <stdint.h>
#include <stddef.h>

#include "slots.h"  /* SLOTS_CRED_ID_LEN, SLOTS_RP_ID_HASH_LEN */

#define CREDSTORE_PUBKEY_LEN    32u
#define CREDSTORE_SIG_LEN       64u
#define CREDSTORE_CRED_ID_LEN   SLOTS_CRED_ID_LEN   /* 18 B */

/* Opaque handle returned by credstore_make / credstore_lookup. Internally
 * just the slot index (0..31), but callers should treat it as opaque so
 * we can change the representation later. */
typedef int credstore_handle_t;

#define CREDSTORE_INVALID_HANDLE (-1)

/**
 * @brief Initialize the credential store.
 *        Calls slots_init() and ensures the TROPIC01 monotonic counter 0
 *        is set to MAX (for the shared signCount). Idempotent.
 *
 * @return 0 on success; negative on TROPIC01 error.
 */
int credstore_init(void);

/**
 * @brief Create a new credential — generate fresh Ed25519 keypair on
 *        TROPIC01, allocate a slot, persist metadata, return the bits
 *        the host's MakeCredential response needs.
 *
 *   1. slots_alloc(rp_id_hash, alg) — picks free slot, writes R-mem
 *   2. tropic_ecc_erase(slot)       — idempotent clean
 *   3. tropic_ecc_generate(slot, CURVE_ED25519)
 *   4. tropic_ecc_pubkey_read(slot, out_pubkey, 32)
 *
 * Power-loss between (1) and (4) leaves an orphan with valid R-mem +
 * empty ECC slot — future GetAssertion for the credId fails at sign-
 * time (returns CTAP2 error). Recoverable via factory_reset.
 *
 * If (2-4) fail, credstore_make rolls back the slots allocation
 * (slots_erase) so the bitmap stays consistent.
 *
 * @param  rp_id_hash    SHA-256(rpId) — 32 bytes
 * @param  alg           Currently must be 8 (Ed25519 / COSE -8); other
 *                       values rejected with CTAP2_ERR_UNSUPPORTED_ALGORITHM
 * @param  out_pubkey    32-byte Ed25519 public key
 * @param  out_cred_id   18-byte credentialId for the relying party
 * @param  out_handle    Handle for the immediate MakeCred self-attestation
 *                       sign — pass to credstore_sign.
 * @return 0 on success; -1 if out of slots; -2 on chip error
 */
int credstore_make(const uint8_t rp_id_hash[SLOTS_RP_ID_HASH_LEN],
                   uint8_t alg,
                   const uint8_t *user_handle, size_t user_handle_len,
                   uint8_t out_pubkey[CREDSTORE_PUBKEY_LEN],
                   uint8_t out_cred_id[CREDSTORE_CRED_ID_LEN],
                   credstore_handle_t *out_handle);

/**
 * @brief Resolve a credential ID from a relying party to an internal
 *        handle for signing.
 *
 *   1. slots_lookup_by_credid — validates version/slot_idx/nonce CT-cmp
 *   2. Returns the slot index as a handle
 *
 * @return 0 on success (out_handle populated); -1 if not found
 */
int credstore_lookup(const uint8_t *cred_id, size_t cred_id_len,
                     credstore_handle_t *out_handle);

/**
 * @brief Sign a message with the Ed25519 key in the slot identified by
 *        the handle. The chip performs the EdDSA computation — private
 *        key never leaves TROPIC01.
 *
 * @param  h           Handle from credstore_make / credstore_lookup
 * @param  msg         Bytes to sign (typically authData || clientDataHash)
 * @param  msg_len     Length of msg (max 4096 per TROPIC01 spec)
 * @param  out_sig     64-byte signature buffer
 * @return 0 on success; -1 on parameter error; -2 on chip error
 */
int credstore_sign(credstore_handle_t h,
                   const uint8_t *msg, size_t msg_len,
                   uint8_t out_sig[CREDSTORE_SIG_LEN]);

/**
 * @brief Peek the signCount that the next assertion will use.
 *        Internally reads TROPIC01 mcounter 0 and returns
 *        TR01_MCOUNTER_VALUE_MAX - current_chip_value, so the result
 *        increases over time. Returns 0 if the chip read fails (logged).
 */
uint32_t credstore_peek_signcount(void);

/**
 * @brief Commit the signCount advance. Decrements TROPIC01 mcounter 0,
 *        which causes credstore_peek_signcount to return a value one
 *        higher next time.
 */
void credstore_commit_signcount(void);

/* ===== Phase 6 M3: read + delete helpers for credentialManagement ===== */

/**
 * @brief Read public key for the credential in the given slot.
 * @return 0 on success; -1 on chip error.
 */
int credstore_get_pubkey(int slot_idx,
                         uint8_t out_pubkey[CREDSTORE_PUBKEY_LEN]);

/**
 * @brief Erase a single credential — ECC slot + R-mem slot, clear bitmap.
 *        Uses the mutation-busy lock (see credstore_is_mutating).
 * @return 0 on success; -1 on out-of-range; -2 on chip error.
 */
int credstore_erase_slot(int slot_idx);

/**
 * @brief True while a credstore-mutating operation is in flight (currently
 *        only credstore_make and credstore_erase_slot raise it).  Used by
 *        MakeCred/GetAssertion to refuse concurrent activity per H2.
 */
int credstore_is_mutating(void);

/**
 * @brief Factory reset: wipe ALL credentials.
 *
 *   1. tropic_ecc_erase(slot) for each of the 32 ECC slots — destroys
 *      chip-side private keys.
 *   2. slots_factory_reset() — clears the R-mem bitmap + every per-
 *      credential R-mem entry + PIN state + M&D state.
 *
 * After this, the authenticator looks like a fresh device. Used by
 * authenticatorReset (CTAP2 cmd 0x07) and by the lt-rpc debug
 * SLOTS_RESET command.
 *
 * @return 0 on success; negative on chip error.
 */
int credstore_factory_reset(void);

#endif /* NIXTROPIC_FIDO_HID_CREDSTORE_H */
