/*
 * CTAP2 MakeCredential (0x01) + GetAssertion (0x02) — Phase 5 M2.
 *
 * Backed by TROPIC01 ECC slots via credstore.h. The private keys
 * generated by lt_ecc_key_generate live entirely on the secure element;
 * STM32 firmware never sees them, signs them, or stores them.
 *
 * Authenticator-data layout (WebAuthn §6.5.1):
 *
 *   offset  size   field
 *   ------  ----   -----
 *      0    32     rpIdHash (SHA-256 of rpId)
 *     32     1     flags
 *                    bit 0 (UP)  user-presence — stubbed true
 *                    bit 2 (UV)  user-verified — we leave 0 (M3 will set)
 *                    bit 6 (AT)  attested-credential-data present
 *                                (MakeCredential only)
 *                    bit 7 (ED)  extensions present
 *     33     4     signCount (big-endian uint32, from TROPIC01 mcounter 0)
 *     37   var     attestedCredentialData (if AT bit set)
 *                    {
 *                       aaguid       16 B
 *                       credIdLen     2 B BE      (always 18 in Phase 5)
 *                       credId       credIdLen B
 *                       credPubKey   var (COSE_Key)
 *                    }
 *
 * Signature input = authData || clientDataHash.
 *
 * MakeCredential response (CBOR map):
 *   { 1: "packed", 2: authData, 3: { alg: -8, sig: <64 B> } }
 *
 * GetAssertion response (CBOR map):
 *   { 1: { id: <credId>, type: "public-key" },
 *     2: authData,
 *     3: <64 B sig> }
 *
 * Phase 5 self-attestation: we sign with the credential's own freshly-
 * generated key. No batch attestation cert chain in the response (no
 * key 5). Spec-compliant for "packed" self-attestation per WebAuthn
 * §8.2 (when the AAGUID is reserved for self-attestation).
 */

#include "ctap2.h"
#include "credstore.h"
#include "cbor.h"
#include "proto.h"
#include "pin.h"
#include "user_presence.h"

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <assert.h>

/* trezor_crypto SHA-256. */
#include "sha2.h"

/* AAGUID exported from ctap2.c. Duplicate definition would shadow.
 * Borrow via extern. */
extern const uint8_t NIXTROPIC_AAGUID[16];

/* Worst-case COSE_Key size for the keys we encode.
 *   Ed25519 (OKP): 4-entry map = 46 bytes
 *   ES256  (EC2):  5-entry map = 81 bytes (reserved for future P-256)
 * Pick a safe maximum covering both. cpp-reviewer audit 2026-05-11 H3. */
#define COSE_KEY_MAX  96u

/* ----- Helpers ----- */

static void be32_store(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)(v >> 24);
    p[1] = (uint8_t)(v >> 16);
    p[2] = (uint8_t)(v >>  8);
    p[3] = (uint8_t) v;
}

/* COSE_Key for Ed25519 public key. CBOR map with integer keys in
 * canonical (length-then-byte) order:
 *
 *   1 → kty = 1   (OKP)
 *   3 → alg = -8  (EdDSA)
 *  -1 → crv = 6   (Ed25519)
 *  -2 → x          (32-byte public key)
 *
 * Encoded keys: 0x01, 0x03, 0x20, 0x21 — already in ascending byte
 * order, so writing them in the natural numeric order produces
 * canonical output. */
static int build_cose_ed25519(const uint8_t *pubkey, uint8_t *out, size_t out_max)
{
    cbor_writer_t w;
    cbor_writer_init(&w, out, out_max);
    cbor_write_map_header(&w, 4);
    cbor_write_uint(&w, 1);   cbor_write_uint(&w, 1);     /* kty: OKP */
    cbor_write_uint(&w, 3);   cbor_write_negint(&w, -8);  /* alg: EdDSA */
    cbor_write_negint(&w, -1); cbor_write_uint(&w, 6);    /* crv: Ed25519 */
    cbor_write_negint(&w, -2); cbor_write_byte_string(&w, pubkey, CREDSTORE_PUBKEY_LEN);
    if (cbor_writer_error(&w)) return -1;
    return (int) cbor_writer_len(&w);
}

/* ----- Request parsing ----- */

/* Minimal MakeCredential request parser. We extract:
 *   key 1: clientDataHash (32 B)
 *   key 2: rp.id (text string)
 *   key 4: pubKeyCredParams must contain at least one supported alg
 *   key 8: pinAuth (optional, 16 B)
 *   key 9: pinProtocol (optional, expected to be 1 if present)
 *
 * Other keys (excludeList, extensions, options) are skipped.
 * excludeList handling is a Phase 5.5+ feature; for M2 we always
 * generate a fresh credential. extensions / options not enforced.
 *
 * Returns 0 on success, negative CTAP2 status on failure. */
static int parse_make_cred(const uint8_t *req, size_t req_len,
                           uint8_t *out_client_hash,
                           const uint8_t **out_rp_id, size_t *out_rp_id_len,
                           int *out_alg,
                           int *out_has_pin_auth, uint8_t out_pin_auth[16],
                           int *out_pin_protocol,
                           const uint8_t **out_user_handle,
                           size_t *out_user_handle_len,
                           int *out_want_credProps)
{
    int alg_found = 0;
    int alg_pref  = 0;        /* selected COSE alg id */
    int got_chash = 0;
    int got_rpid  = 0;
    *out_has_pin_auth = 0;
    *out_pin_protocol = 0;
    *out_user_handle     = NULL;
    *out_user_handle_len = 0;
    *out_want_credProps  = 0;

    cbor_reader_t r;
    cbor_reader_init(&r, req, req_len);

    size_t n_keys;
    if (cbor_reader_read_map_header(&r, &n_keys) < 0) {
        return -(int) CTAP2_ERR_INVALID_CBOR;
    }
    for (size_t i = 0; i < n_keys; ++i) {
        uint8_t  mt;
        uint64_t key;
        if (cbor_reader_read_head(&r, &mt, &key) < 0) {
            return -(int) CTAP2_ERR_INVALID_CBOR;
        }
        if (mt != 0u) {
            return -(int) CTAP2_ERR_CBOR_UNEXPECTED_TYPE;
        }
        if (key == 1u) {
            const uint8_t *p; size_t L;
            if (cbor_reader_read_bytes(&r, &p, &L) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            if (L != 32u) return -(int) CTAP1_ERR_INVALID_LENGTH;
            memcpy(out_client_hash, p, 32);
            got_chash = 1;
        } else if (key == 2u) {
            /* rp = { "id": text, "name"?: text } */
            size_t mc;
            if (cbor_reader_read_map_header(&r, &mc) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            for (size_t j = 0; j < mc; ++j) {
                const uint8_t *kp; size_t kL;
                if (cbor_reader_read_text(&r, &kp, &kL) < 0) {
                    return -(int) CTAP2_ERR_INVALID_CBOR;
                }
                if (kL == 2u && memcmp(kp, "id", 2) == 0) {
                    if (cbor_reader_read_text(&r, out_rp_id, out_rp_id_len) < 0) {
                        return -(int) CTAP2_ERR_INVALID_CBOR;
                    }
                    got_rpid = 1;
                } else {
                    if (cbor_reader_skip(&r) < 0) {
                        return -(int) CTAP2_ERR_INVALID_CBOR;
                    }
                }
            }
        } else if (key == 3u) {
            /* user = { 1:id (bytes), 2:name (text)?, 3:displayName?, 4:icon? }.
             * We persist only id (= user_handle) for Phase 6 M3 (used by
             * authenticatorCredentialManagement enumerateCredentials).
             * Name + displayName deferred to Phase 8. */
            size_t mc;
            if (cbor_reader_read_map_header(&r, &mc) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            for (size_t j = 0; j < mc; ++j) {
                const uint8_t *kp; size_t kL;
                if (cbor_reader_read_text(&r, &kp, &kL) < 0) {
                    return -(int) CTAP2_ERR_INVALID_CBOR;
                }
                if (kL == 2u && memcmp(kp, "id", 2) == 0) {
                    if (cbor_reader_read_bytes(&r, out_user_handle,
                                               out_user_handle_len) < 0) {
                        return -(int) CTAP2_ERR_INVALID_CBOR;
                    }
                } else {
                    if (cbor_reader_skip(&r) < 0) {
                        return -(int) CTAP2_ERR_INVALID_CBOR;
                    }
                }
            }
        } else if (key == 4u) {
            /* pubKeyCredParams = [ { "alg": int, "type": text }, ... ] */
            size_t ac;
            if (cbor_reader_read_array_header(&r, &ac) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            for (size_t j = 0; j < ac; ++j) {
                size_t entries;
                if (cbor_reader_read_map_header(&r, &entries) < 0) {
                    return -(int) CTAP2_ERR_INVALID_CBOR;
                }
                int alg_here = 0;
                for (size_t k = 0; k < entries; ++k) {
                    const uint8_t *kp; size_t kL;
                    if (cbor_reader_read_text(&r, &kp, &kL) < 0) {
                        return -(int) CTAP2_ERR_INVALID_CBOR;
                    }
                    if (kL == 3u && memcmp(kp, "alg", 3) == 0) {
                        uint8_t  m;
                        uint64_t v;
                        if (cbor_reader_read_head(&r, &m, &v) < 0) {
                            return -(int) CTAP2_ERR_INVALID_CBOR;
                        }
                        if (m == 0u) alg_here = (int) v;          /* uint */
                        else if (m == 1u) alg_here = -1 - (int) v; /* negint */
                        else return -(int) CTAP2_ERR_CBOR_UNEXPECTED_TYPE;
                    } else {
                        if (cbor_reader_skip(&r) < 0) {
                            return -(int) CTAP2_ERR_INVALID_CBOR;
                        }
                    }
                }
                /* Pick the first supported alg in the host's preference order. */
                if (!alg_found && (alg_here == -8 || alg_here == -7)) {
                    alg_pref  = alg_here;
                    alg_found = 1;
                }
            }
        } else if (key == 6u) {
            /* extensions = { "<name>": <value>, ... }.  Phase 8 M2:
             * recognise the client-driven `credProps` extension so
             * browsers stop labelling our credentials as "unknown
             * discoverability".  Per WebAuthn L3 §10.4 the value the
             * RP sends is a boolean `true`; we treat any presence of
             * the key as a request to surface credProps in the
             * response.  All other extension names are silently
             * skipped (we don't yet implement credProtect,
             * hmac-secret, etc — those land in later phases). */
            size_t emap;
            if (cbor_reader_read_map_header(&r, &emap) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            for (size_t j = 0; j < emap; ++j) {
                const uint8_t *ep; size_t eL;
                if (cbor_reader_read_text(&r, &ep, &eL) < 0) {
                    return -(int) CTAP2_ERR_INVALID_CBOR;
                }
                if (eL == 9u && memcmp(ep, "credProps", 9) == 0) {
                    /* Value should be CBOR true; we accept any well-
                     * formed value because the presence of the key
                     * alone is the spec-defined trigger. */
                    if (cbor_reader_skip(&r) < 0) {
                        return -(int) CTAP2_ERR_INVALID_CBOR;
                    }
                    *out_want_credProps = 1;
                } else {
                    if (cbor_reader_skip(&r) < 0) {
                        return -(int) CTAP2_ERR_INVALID_CBOR;
                    }
                }
            }
        } else if (key == 8u) {
            /* pinAuth = 16 B */
            const uint8_t *p; size_t L;
            if (cbor_reader_read_bytes(&r, &p, &L) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            if (L != 16u) return -(int) CTAP2_ERR_PIN_AUTH_INVALID;
            memcpy(out_pin_auth, p, 16);
            *out_has_pin_auth = 1;
        } else if (key == 9u) {
            /* pinProtocol (uint) */
            uint8_t m2; uint64_t v;
            if (cbor_reader_read_head(&r, &m2, &v) < 0 || m2 != 0u) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            *out_pin_protocol = (int) v;
        } else {
            if (cbor_reader_skip(&r) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
        }
    }

    if (!got_chash || !got_rpid) {
        return -(int) CTAP2_ERR_MISSING_PARAMETER;
    }
    if (!alg_found) {
        return -(int) CTAP2_ERR_UNSUPPORTED_ALGORITHM;
    }
    /* M2 only signs with Ed25519 — refuse ES256 even if advertised. */
    if (alg_pref != -8) {
        return -(int) CTAP2_ERR_UNSUPPORTED_ALGORITHM;
    }
    *out_alg = alg_pref;
    return 0;
}

/* GetAssertion request parser. Extracts:
 *   key 1: rpId (text)
 *   key 2: clientDataHash (32 B)
 *   key 3: allowList — array of { 1: <credId>, 2: "public-key" };
 *          we pick the first credId we recognize (resident-key flow)
 *   key 6: pinAuth (optional, 16 B)
 *   key 7: pinProtocol (optional uint)
 *
 * On exit out_cred_id_p / out_cred_id_len point into req[] (no copy).
 * If allowList was absent or empty, *out_cred_id_p stays NULL —
 * caller should reject with NO_CREDENTIALS (M2 has no resident-
 * discovery yet; that's M3+).
 */
static int parse_get_assertion(const uint8_t *req, size_t req_len,
                               uint8_t *out_client_hash,
                               const uint8_t **out_rp_id, size_t *out_rp_id_len,
                               const uint8_t **out_cred_id_p, size_t *out_cred_id_len,
                               int *out_has_pin_auth, uint8_t out_pin_auth[16],
                               int *out_pin_protocol)
{
    int got_chash = 0;
    int got_rpid  = 0;
    *out_cred_id_p = NULL;
    *out_cred_id_len = 0;
    *out_has_pin_auth = 0;
    *out_pin_protocol = 0;

    cbor_reader_t r;
    cbor_reader_init(&r, req, req_len);

    size_t n_keys;
    if (cbor_reader_read_map_header(&r, &n_keys) < 0) {
        return -(int) CTAP2_ERR_INVALID_CBOR;
    }
    for (size_t i = 0; i < n_keys; ++i) {
        uint8_t mt; uint64_t key;
        if (cbor_reader_read_head(&r, &mt, &key) < 0 || mt != 0u) {
            return -(int) CTAP2_ERR_INVALID_CBOR;
        }
        if (key == 1u) {
            if (cbor_reader_read_text(&r, out_rp_id, out_rp_id_len) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            got_rpid = 1;
        } else if (key == 2u) {
            const uint8_t *p; size_t L;
            if (cbor_reader_read_bytes(&r, &p, &L) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            if (L != 32u) return -(int) CTAP1_ERR_INVALID_LENGTH;
            memcpy(out_client_hash, p, 32);
            got_chash = 1;
        } else if (key == 3u) {
            /* allowList = [ { 1: <credId bytes>, 2: "public-key" }, ... ]
             * Iterate until we find a credId byte-string. We don't yet
             * filter by validity here — credstore_lookup will reject
             * unknown credIds and we'll return NO_CREDENTIALS if no
             * entry matches. For M2 we just snapshot the first entry. */
            size_t ac;
            if (cbor_reader_read_array_header(&r, &ac) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            for (size_t j = 0; j < ac; ++j) {
                size_t entries;
                if (cbor_reader_read_map_header(&r, &entries) < 0) {
                    return -(int) CTAP2_ERR_INVALID_CBOR;
                }
                for (size_t k = 0; k < entries; ++k) {
                    const uint8_t *kp; size_t kL;
                    if (cbor_reader_read_text(&r, &kp, &kL) < 0) {
                        return -(int) CTAP2_ERR_INVALID_CBOR;
                    }
                    if (kL == 2u && memcmp(kp, "id", 2) == 0) {
                        const uint8_t *idp; size_t idL;
                        if (cbor_reader_read_bytes(&r, &idp, &idL) < 0) {
                            return -(int) CTAP2_ERR_INVALID_CBOR;
                        }
                        if (*out_cred_id_p == NULL) {
                            *out_cred_id_p   = idp;
                            *out_cred_id_len = idL;
                        }
                    } else {
                        if (cbor_reader_skip(&r) < 0) {
                            return -(int) CTAP2_ERR_INVALID_CBOR;
                        }
                    }
                }
            }
        } else if (key == 6u) {
            /* pinAuth */
            const uint8_t *p; size_t L;
            if (cbor_reader_read_bytes(&r, &p, &L) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            if (L != 16u) return -(int) CTAP2_ERR_PIN_AUTH_INVALID;
            memcpy(out_pin_auth, p, 16);
            *out_has_pin_auth = 1;
        } else if (key == 7u) {
            /* pinProtocol */
            uint8_t m2; uint64_t v;
            if (cbor_reader_read_head(&r, &m2, &v) < 0 || m2 != 0u) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
            *out_pin_protocol = (int) v;
        } else {
            if (cbor_reader_skip(&r) < 0) {
                return -(int) CTAP2_ERR_INVALID_CBOR;
            }
        }
    }
    if (!got_chash || !got_rpid) {
        return -(int) CTAP2_ERR_MISSING_PARAMETER;
    }
    return 0;
}

/* ----- AuthData builder ----- */

#define FLAG_UP  0x01u
#define FLAG_UV  0x04u   /* user-verified (Phase 5 M3: set when pinAuth verified) */
#define FLAG_AT  0x40u
#define FLAG_ED  0x80u   /* extension data present (CTAP2 §6.1) */

static int build_authdata(const uint8_t *rp_id_hash, uint8_t flags,
                          uint32_t sign_count,
                          const uint8_t *cred_id, size_t cred_id_len,
                          const uint8_t *cose_pubkey, size_t cose_pubkey_len,
                          uint8_t *out, size_t out_max)
{
    /* base size = 32 + 1 + 4 = 37; with AT also +16 +2 +credIdLen +pkLen */
    size_t need = 37u;
    int have_at = (flags & FLAG_AT) != 0;
    if (have_at) {
        need += 16u + 2u + cred_id_len + cose_pubkey_len;
    }
    if (need > out_max) return -1;

    size_t off = 0;
    memcpy(&out[off], rp_id_hash, 32); off += 32u;
    out[off++] = flags;
    be32_store(&out[off], sign_count); off += 4u;

    if (have_at) {
        memcpy(&out[off], NIXTROPIC_AAGUID, 16); off += 16u;
        out[off++] = (uint8_t)(cred_id_len >> 8);
        out[off++] = (uint8_t) cred_id_len;
        memcpy(&out[off], cred_id, cred_id_len); off += cred_id_len;
        memcpy(&out[off], cose_pubkey, cose_pubkey_len); off += cose_pubkey_len;
    }

    return (int) off;
}

/* ----- Handlers ----- */

int ctap2_make_credential(const uint8_t *req, size_t req_len,
                          uint8_t *resp, size_t resp_max)
{
    uint8_t client_hash[32];
    const uint8_t *rp_id_p = NULL;
    size_t  rp_id_len = 0;
    int     alg = 0;
    int     has_pin_auth = 0;
    uint8_t pin_auth_in[16] = {0};
    int     pin_protocol = 0;
    const uint8_t *user_handle_p = NULL;
    size_t  user_handle_len = 0;
    int     want_credProps = 0;

    int err = parse_make_cred(req, req_len, client_hash,
                              &rp_id_p, &rp_id_len, &alg,
                              &has_pin_auth, pin_auth_in, &pin_protocol,
                              &user_handle_p, &user_handle_len,
                              &want_credProps);
    if (err < 0) {
        resp[0] = (uint8_t)(-err);
        return 1;
    }

    /* PIN gating per CTAP2 §5.1 step 4:
     *   - If PIN is set on this authenticator AND request has no pinAuth:
     *       reject with CTAP2_ERR_PIN_REQUIRED.
     *   - If pinAuth IS present:
     *       verify pinProtocol == 1 AND token verifies AND in-boot
     *       lockout not active. Otherwise PIN_AUTH_INVALID.
     *   - If both above pass: set UV bit in authData.
     *
     * Edge case: pinAuth provided but PIN not set on device. CTAP2 says
     * authenticator MAY reject; we accept and ignore (since the token
     * couldn't have been minted without setPin first). */
    uint8_t uv_flag = 0;
    if (has_pin_auth) {
        if (pin_protocol != (int) PIN_PROTOCOL_VERSION) {
            resp[0] = CTAP1_ERR_INVALID_PARAMETER; return 1;
        }
        if (pin_verify_pinauth(pin_auth_in, client_hash) != 0) {
            resp[0] = CTAP2_ERR_PIN_AUTH_INVALID; return 1;
        }
        uv_flag = FLAG_UV;
    } else if (pin_is_set()) {
        resp[0] = CTAP2_ERR_PIN_REQUIRED; return 1;
    }

    /* Phase 6 M3 (H2 defense): refuse if credstore is mid-mutation
     * (concurrent credentialManagement deleteCredential or another
     * MakeCred on a different CID).  CTAPHID layer typically serialises
     * but a tud_task pump during this window could deliver a competing
     * frame; bounce it cleanly rather than racing on the bitmap. */
    if (credstore_is_mutating()) {
        resp[0] = CTAP2_ERR_NOT_ALLOWED;
        return 1;
    }

    /* Phase 6 M1: real user-presence — replaces Phase 5 stub-true.
     * Placed BEFORE credstore_make so a refused/timed-out prompt does
     * not waste an ECC slot.  H5 sign-canary compare — `up != UP_OK`
     * defends against single-instruction skip of this check. */
    up_result_t up = user_presence_check(30000u);
    if (up != UP_OK) {
        resp[0] = CTAP2_ERR_OPERATION_DENIED;
        return 1;
    }

    /* rpIdHash = SHA-256(rpId) */
    uint8_t rp_id_hash[32];
    sha256_Raw(rp_id_p, (uint32_t) rp_id_len, rp_id_hash);

    /* Allocate slot + generate fresh Ed25519 keypair on TROPIC01.
     * (alg = -8 in CTAP2; credstore_make takes COSE 8 = Ed25519.) */
    uint8_t pubkey[CREDSTORE_PUBKEY_LEN];
    uint8_t cred_id[CREDSTORE_CRED_ID_LEN];
    credstore_handle_t handle = CREDSTORE_INVALID_HANDLE;
    int mk_rc = credstore_make(rp_id_hash, 8u,
                               user_handle_p, user_handle_len,
                               pubkey, cred_id, &handle);
    if (mk_rc == -1) {
        /* slots_alloc returned full */
        resp[0] = CTAP2_ERR_KEY_STORE_FULL;
        return 1;
    } else if (mk_rc != 0) {
        resp[0] = CTAP2_ERR_OTHER;
        return 1;
    }

    /* COSE-encoded public key */
    uint8_t cose_pub[COSE_KEY_MAX];
    static_assert(sizeof cose_pub >= 46u,
                  "cose_pub must hold at least the 46-byte Ed25519 COSE_Key");
    int cose_pub_len = build_cose_ed25519(pubkey, cose_pub, sizeof cose_pub);
    if (cose_pub_len < 0) {
        resp[0] = CTAP2_ERR_OTHER;
        return 1;
    }

    /* authData with AT bit set. UV bit reflects PIN verification status.
     * Peek-then-commit the signCount so a failed build doesn't desync
     * the on-chip counter. */
    uint32_t sc = credstore_peek_signcount();
    uint8_t auth_data[256];
    uint8_t auth_flags = FLAG_UP | uv_flag | FLAG_AT;
    if (want_credProps) {
        auth_flags |= FLAG_ED;
    }
    int auth_data_len = build_authdata(rp_id_hash, auth_flags,
                                       sc,
                                       cred_id, CREDSTORE_CRED_ID_LEN,
                                       cose_pub, (size_t) cose_pub_len,
                                       auth_data, sizeof auth_data);
    if (auth_data_len < 0) {
        resp[0] = CTAP2_ERR_OTHER;
        return 1;
    }

    /* Phase 8 M2 — append extensions area when credProps was requested.
     * Wire layout per CTAP2.1 §6.1:
     *   authData = rpIdHash || flags || signCount
     *              || (attestedCredentialData if AT)
     *              || (extensions CBOR map if ED)
     *
     * Our extensions map carries one entry:
     *   { "credProps": { "rk": true } }
     *
     * Every credential we mint is resident (TROPIC01 R-mem slot
     * indexed by `slot_idx` is the storage), so `rk` is always true.
     * If we ever support non-discoverable creds we'd source the
     * value from the request's options.rk instead. */
    if (want_credProps) {
        cbor_writer_t ew;
        cbor_writer_init(&ew,
                         &auth_data[auth_data_len],
                         sizeof auth_data - (size_t) auth_data_len);
        cbor_write_map_header(&ew, 1);
        cbor_write_text(&ew, "credProps");
        cbor_write_map_header(&ew, 1);
        cbor_write_text(&ew, "rk");
        cbor_write_bool(&ew, true);
        if (cbor_writer_error(&ew)) {
            resp[0] = CTAP2_ERR_OTHER;
            return 1;
        }
        auth_data_len += (int) cbor_writer_len(&ew);
    }

    /* Signature over authData || clientDataHash, signed by the fresh
     * credential's own key (self-attestation packed format). */
    uint8_t sig_input[sizeof auth_data + 32];
    memcpy(sig_input, auth_data, (size_t) auth_data_len);
    memcpy(&sig_input[auth_data_len], client_hash, 32);
    uint8_t sig[CREDSTORE_SIG_LEN];
    if (credstore_sign(handle, sig_input, (size_t) auth_data_len + 32u, sig) != 0) {
        resp[0] = CTAP2_ERR_OTHER;
        return 1;
    }
    credstore_commit_signcount();

    /* Build attestation response.
     * { 1: "packed", 2: authData, 3: { alg: -8, sig: sig } } */
    if (resp_max < 1u) return -1;
    resp[0] = CTAP2_OK;

    cbor_writer_t w;
    cbor_writer_init(&w, &resp[1], resp_max - 1u);
    cbor_write_map_header(&w, 3);

    cbor_write_uint(&w, 1);
    cbor_write_text(&w, "packed");

    cbor_write_uint(&w, 2);
    cbor_write_byte_string(&w, auth_data, (size_t) auth_data_len);

    cbor_write_uint(&w, 3);
    cbor_write_map_header(&w, 2);
    cbor_write_text(&w, "alg");
    cbor_write_negint(&w, -8);
    cbor_write_text(&w, "sig");
    cbor_write_byte_string(&w, sig, CREDSTORE_SIG_LEN);

    if (cbor_writer_error(&w)) {
        resp[0] = CTAP2_ERR_OTHER;
        return 1;
    }
    return (int)(1u + cbor_writer_len(&w));
}

int ctap2_get_assertion(const uint8_t *req, size_t req_len,
                        uint8_t *resp, size_t resp_max)
{
    uint8_t client_hash[32];
    const uint8_t *rp_id_p = NULL;
    size_t  rp_id_len = 0;
    const uint8_t *cred_id_p = NULL;
    size_t  cred_id_len = 0;
    int     has_pin_auth = 0;
    uint8_t pin_auth_in[16] = {0};
    int     pin_protocol = 0;

    int err = parse_get_assertion(req, req_len,
                                  client_hash,
                                  &rp_id_p, &rp_id_len,
                                  &cred_id_p, &cred_id_len,
                                  &has_pin_auth, pin_auth_in, &pin_protocol);
    if (err < 0) {
        resp[0] = (uint8_t)(-err);
        return 1;
    }

    /* PIN gating — same shape as MakeCred. */
    uint8_t uv_flag = 0;
    if (has_pin_auth) {
        if (pin_protocol != (int) PIN_PROTOCOL_VERSION) {
            resp[0] = CTAP1_ERR_INVALID_PARAMETER; return 1;
        }
        if (pin_verify_pinauth(pin_auth_in, client_hash) != 0) {
            resp[0] = CTAP2_ERR_PIN_AUTH_INVALID; return 1;
        }
        uv_flag = FLAG_UV;
    } else if (pin_is_set()) {
        resp[0] = CTAP2_ERR_PIN_REQUIRED; return 1;
    }

    if (cred_id_p == NULL) {
        /* allowList absent or empty. M2 doesn't support resident
         * discovery (no allowList → "find any credential matching
         * rpId"); that's M3+. For now: NO_CREDENTIALS. */
        resp[0] = CTAP2_ERR_NO_CREDENTIALS;
        return 1;
    }

    /* Phase 6 M3 (H2 defense): refuse if credstore is mid-mutation.
     * Same rationale as MakeCred. */
    if (credstore_is_mutating()) {
        resp[0] = CTAP2_ERR_NOT_ALLOWED;
        return 1;
    }

    credstore_handle_t handle = CREDSTORE_INVALID_HANDLE;
    if (credstore_lookup(cred_id_p, cred_id_len, &handle) != 0) {
        resp[0] = CTAP2_ERR_NO_CREDENTIALS;
        return 1;
    }

    /* Phase 6 M1: real user-presence — replaces Phase 5 stub-true.
     * Placed AFTER credstore_lookup so we don't prompt for missing
     * credentials (spec: CTAP2 §6.1.2 step 11 requires lookup first).
     * Placed BEFORE peek_signcount so a refused prompt doesn't advance
     * the monotonic counter. */
    up_result_t up = user_presence_check(30000u);
    if (up != UP_OK) {
        resp[0] = CTAP2_ERR_OPERATION_DENIED;
        return 1;
    }

    uint8_t rp_id_hash[32];
    sha256_Raw(rp_id_p, (uint32_t) rp_id_len, rp_id_hash);

    /* authData WITHOUT attestedCredentialData. UP always set (real now);
     * UV set iff pinAuth verified. */
    uint32_t sc = credstore_peek_signcount();
    uint8_t auth_data[64];
    int auth_data_len = build_authdata(rp_id_hash, FLAG_UP | uv_flag,
                                       sc,
                                       NULL, 0, NULL, 0,
                                       auth_data, sizeof auth_data);
    if (auth_data_len < 0) {
        resp[0] = CTAP2_ERR_OTHER;
        return 1;
    }

    /* sigInput = authData || clientDataHash */
    uint8_t sig_input[sizeof auth_data + 32];
    memcpy(sig_input, auth_data, (size_t) auth_data_len);
    memcpy(&sig_input[auth_data_len], client_hash, 32);
    uint8_t sig[CREDSTORE_SIG_LEN];
    if (credstore_sign(handle, sig_input, (size_t) auth_data_len + 32u, sig) != 0) {
        resp[0] = CTAP2_ERR_OTHER;
        return 1;
    }
    credstore_commit_signcount();

    /* Response:
     * { 1: { id: credId, type: "public-key" },
     *   2: authData,
     *   3: signature }
     */
    if (resp_max < 1u) return -1;
    resp[0] = CTAP2_OK;

    cbor_writer_t w;
    cbor_writer_init(&w, &resp[1], resp_max - 1u);
    cbor_write_map_header(&w, 3);

    cbor_write_uint(&w, 1);
    cbor_write_map_header(&w, 2);
    cbor_write_text(&w, "id");
    cbor_write_byte_string(&w, cred_id_p, cred_id_len);
    cbor_write_text(&w, "type");
    cbor_write_text(&w, "public-key");

    cbor_write_uint(&w, 2);
    cbor_write_byte_string(&w, auth_data, (size_t) auth_data_len);

    cbor_write_uint(&w, 3);
    cbor_write_byte_string(&w, sig, CREDSTORE_SIG_LEN);

    if (cbor_writer_error(&w)) {
        resp[0] = CTAP2_ERR_OTHER;
        return 1;
    }
    return (int)(1u + cbor_writer_len(&w));
}
